name: its_urgent
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.1
  flutter_riverpod: ^2.5.1
  go_router: ^14.1.3
  firebase_auth: ^4.19.6
  google_fonts: ^6.2.1
  firebase_ui_auth: ^1.14.0
  pinput: ^5.0.0
  flutter_libphonenumber: ^2.2.3
  transparent_image: ^2.0.1
  image_picker: ^1.1.2
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/

